#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

echo "Removing 0 and VTKs"
rm -rf 0 VTKs constant/polyMesh.base constant/polyMesh
rm *png *csv *txt
