#!/bin/bash

# Load OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

# Serial steps
runApplication blockMesh
runApplication setFields

# Decompose domain
runApplication decomposePar

# Run simulation (timed)
echo "Running laserbeamFoam in parallel on 4 cores..."
/usr/bin/time -f "\n=== Timing ===\nElapsed time: %E\nUser time: %U\nCPU usage: %P" \
mpirun --oversubscribe -np 4 laserbeamFoam -parallel > log.laserbeamFoam 2> log.laserbeamFoam.time

# Reconstruction
echo "Reconstructing..."
reconstructParMesh -constant > log.reconstructParMesh
reconstructPar > log.reconstructPar

# Clean up
rm -r processor*/
touch case.foam

echo "Done."

