#!/bin/bash

# Load OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#echo "Copying 'initial' to 0"
#cp -r initial 0

# Serial steps
#runApplication blockMesh
#runApplication setFields

# Decompose domain
runApplication decomposePar

# Run simulation (timed)
echo "Running laserbeamFoam in parallel on 16 cores..."
/usr/bin/time -f "\n=== Timing ===\nElapsed time: %E\nUser time: %U\nCPU usage: %P" \
mpirun --oversubscribe -np 16 laserbeamFoam -parallel > log.laserbeamFoam 2> log.laserbeamFoam.time

# Reconstruction
echo "Reconstructing..."
# Time reconstructParMesh
/usr/bin/time -f "\n=== reconstructParMesh Timing ===\nElapsed time: %E\nUser time: %U\nCPU usage: %P" \
reconstructParMesh -constant > log.reconstructParMesh 2>> log.laserbeamFoam.time

# Time reconstructPar
/usr/bin/time -f "\n=== reconstructPar Timing ===\nElapsed time: %E\nUser time: %U\nCPU usage: %P" \
reconstructPar > log.reconstructPar 2>> log.laserbeamFoam.time

# Clean up
#rm -r processor*/
touch case.foam

echo "Done."

